# Use an official Node.js runtime as the base image
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY ./package*.json ./

# Install the project dependencies
RUN npm install

# Copy the entire project to the container
COPY ./ ./

# Build the Next.js app
RUN npm run build
EXPOSE 3000
# Set the command to start the Next.js app
CMD ["npm", "start"]
